<?php

namespace App\DataFixtures;

use App\Entity\Profile;
use App\Entity\Skill;
use App\Entity\Testimonials;
use App\Entity\User;
use App\Repository\TestimonialsRepository;
use App\Services\TokenGenerator;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Faker\Generator;
use Faker\Provider\Internet;
use Faker\Provider\Person;
use Faker\Provider\PhoneNumber;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class AppFixtures extends Fixture
{
    /**
     * @var array
     */
    private array $users;
    /**
     * @var UserPasswordEncoderInterface
     */
    private UserPasswordEncoderInterface $encoder;

    /**
     * @var array $user_reviews
     */
    private array $user_reviews;

    /**
     * AppFixtures constructor.
     * @param UserPasswordEncoderInterface $encoder
     */
    public function __construct(UserPasswordEncoderInterface $encoder)
    {
        $this->encoder = $encoder;
    }

    /**
     * @param ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $this->loadUsers($manager);
        $this->loadSkills($manager);
        $this->loadTestimonials($manager);
        $this->loadRating($manager);
    }

    /**
     * @param ObjectManager $manager
     */
    public function loadUsers(ObjectManager $manager)
    {
        $faker = new Generator();
        $faker->addProvider(new Internet($faker));
        $faker->addProvider(new Person($faker));
        $faker->addProvider(new PhoneNumber($faker));
        $tokenGenerator = new TokenGenerator();

        for ($i = 0; $i < 100; $i++) {
            $user = new User();
            $profile = new Profile();
            $active = rand(0,1);

            $user->setEmail($faker->freeEmail());
            $user->setPassword($this->encoder->encodePassword($user,'111111'));
            $user->setUsername($faker->userName());
            if($active) {
                $user->setActive(true);
                $user->setSessionToken( $tokenGenerator->generateToken(50) );
                $profile->setSurname($faker->lastName());
                $profile->setPhone($faker->phoneNumber());
            }else{
                $user->setActivationToken($tokenGenerator->generateToken(50));
            }

            $profile->setName($faker->firstName());
            $profile->setUser($user);
            $profile->setMentor(rand(0,1));
            $user->setProfile($profile);

            $manager->persist($user);
            $manager->persist($profile);
            $manager->flush();

            $this->users[] = $user;
        }
    }

    /**
     * @param ObjectManager $manager
     */
    public function loadSkills(ObjectManager $manager)
    {
        $skills = ['js', 'php', 'c#', 'c', 'c++', 'abode photoshop', 'algorithms', 'data scents'];

        foreach ($skills as $item) {
            $skill = new Skill();
            $skill->setName($item);
            $skill->setValid(true);

            $manager->persist($skill);
            foreach ($this->users as /** @var User $user */ $user) {
                if(rand(0,1)) {
                    $user->getSkills()->add($skill);
                }
            }
            $manager->flush();
        }
    }

    /**
     * @param ObjectManager $manager
     */
    public function loadTestimonials(ObjectManager $manager)
    {

        for ($i = 0; $i < 100; $i++) {
            $users = $this->getUsers();

            $testimonial = new Testimonials();
            $testimonial->setRating(rand(1,5));
            $testimonial->setUserTo($users['user_to']);
            $testimonial->setUserFrom($users['user_from']);
            $testimonial->setText('lorem ipsum');

            $manager->persist($testimonial);
            $manager->flush();
        }
    }

    /**
     * @param ObjectManager $manager
     */
    public function loadRating(ObjectManager $manager)
    {
        /** @var TestimonialsRepository $repository */
        $repository = $manager->getRepository(Testimonials::class);
        $reviews = $repository->findAll();

        foreach ($reviews as $review) {
            if(rand(0,1)) {
                $review->setVerified(true);
                $manager->persist($review);
                $manager->flush();
            }
            
        }

    }

    /**
     * @param string $name
     * @param object $object
     */
    public function addReference($name, $object)
    {
        parent::addReference($name, $object); // TODO: Change the autogenerated stub
    }

    /**
     * @return User[]
     */
    private function getUsers() : array
    {
        $users_count = count($this->users) - 1;

        /** @var User $user_from */
        $user_from = $this->users[rand(0,$users_count)];

        /** @var User $user_to */
        $user_to = $this->users[rand(0,$users_count)];

        if(
            isset($this->user_reviews["{$user_from->getId()}_{$user_to->getId()}"])
        ) {
            return $this->getUsers();
        }

        $this->user_reviews["{$user_from->getId()}_{$user_to->getId()}"] = 1;

        return [
            'user_from' => $user_from,
            'user_to'   => $user_to
        ];

    }
}
